step-restore-cache: &step-restore-cache
  restore_cache:
    keys:
      - v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
      - v1-dependencies-{{ arch }}

steps-test: &steps-test
  steps:
    - run: git config --global core.autocrlf input
    - checkout
    - *step-restore-cache
    - run: yarn --frozen-lockfile
    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
    - run: yarn test

version: 2.1
orbs:
  cfa: continuousauth/npm@1.0.2
jobs:
  test:
    docker:
      - image: circleci/node:14.17
    <<: *steps-test

workflows:
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test
      - cfa/release:
          requires:
            - test
          filters:
            branches:
              only:
                - main
          context: cfa-release
